name: woods1_stool
description: A new Flutter application.

version: 1.0.1+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/


  uses-material-design: true

